package ui;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnOrdenCompra = new javax.swing.JMenuItem();
        btnOrdenVenta = new javax.swing.JMenuItem();
        produccion = new javax.swing.JMenu();
        btnProduccion = new javax.swing.JMenuItem();
        importacion = new javax.swing.JMenu();
        btnImportacion = new javax.swing.JMenuItem();
        facturacion = new javax.swing.JMenu();
        btnFacturacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto UMG");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        jMenu1.setText("Ordenes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        btnOrdenCompra.setText("Orden de compra");
        btnOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenCompraActionPerformed(evt);
            }
        });
        jMenu1.add(btnOrdenCompra);

        btnOrdenVenta.setText("Orden de venta");
        btnOrdenVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenVentaActionPerformed(evt);
            }
        });
        jMenu1.add(btnOrdenVenta);

        jMenuBar1.add(jMenu1);

        produccion.setText("Producción");
        produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionActionPerformed(evt);
            }
        });

        btnProduccion.setText("Ingresar a producción");
        btnProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduccionActionPerformed(evt);
            }
        });
        produccion.add(btnProduccion);

        jMenuBar1.add(produccion);

        importacion.setText("Importación");

        btnImportacion.setText("Ingresar a importaciones");
        btnImportacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportacionActionPerformed(evt);
            }
        });
        importacion.add(btnImportacion);

        jMenuBar1.add(importacion);

        facturacion.setText("Facturación");

        btnFacturacion.setText("Ingresar a facturación");
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        facturacion.add(btnFacturacion);

        jMenuBar1.add(facturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedor.getAccessibleContext().setAccessibleName("contenedor");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btnOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenCompraActionPerformed
       frmOrdenCompra f = new frmOrdenCompra();
       contenedor.add(f);
       f.show();
    }//GEN-LAST:event_btnOrdenCompraActionPerformed

    private void produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionActionPerformed

    }//GEN-LAST:event_produccionActionPerformed

    private void btnProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduccionActionPerformed
        frmProduccion f = new frmProduccion();
        contenedor.add(f);
        f.show();
    }//GEN-LAST:event_btnProduccionActionPerformed

    private void btnImportacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportacionActionPerformed
        frmImportacion f = new frmImportacion();
        contenedor.add(f);
        f.show();
    }//GEN-LAST:event_btnImportacionActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        frmFacturacion f = new frmFacturacion();
        contenedor.add(f);
        f.show();
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnOrdenVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenVentaActionPerformed
        frmOrdenVenta f = new frmOrdenVenta();
        contenedor.add(f);
        f.show();
    }//GEN-LAST:event_btnOrdenVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnFacturacion;
    private javax.swing.JMenuItem btnImportacion;
    private javax.swing.JMenuItem btnOrdenCompra;
    private javax.swing.JMenuItem btnOrdenVenta;
    private javax.swing.JMenuItem btnProduccion;
    private javax.swing.JPanel contenedor;
    private javax.swing.JMenu facturacion;
    private javax.swing.JMenu importacion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu produccion;
    // End of variables declaration//GEN-END:variables
}
